name=input("Enter father's name: ")
birthplace=input("Enter father's birthplace: ")
bmonth=input("Enter birthmoth: ")
bday=int(input("Enter birthday: "))
byear=int(input("Enter birthyear: "))
age=2023-byear

print(" ")
print(name, end = "")
print("'s Information")
print("Name: ", end = "")
print(name)
print("Birthplace: ", end = "")
print(birthplace)
print("Birthday: ", end = "")
print(bmonth, end = "")
print(" ", end = "")
print(bday, end = "")
print(", ", end = "")
print(byear)
print("Age: ", end = "")
print(age)