name=input("Enter student's name: ")
english=int(input("Enter grade for English: "))
filipino=int(input("Enter grade for Filipino: "))
science=int(input("Enter grade for Science: "))
math=int(input("Enter grade for Math: "))
ap=int(input("Enter grade for Araling Panlipunan: "))
pe=int(input("Enter grade for Physical Education: "))
average=float((english+filipino+science+math+ap+pe)/6)

print(" ")
print(name, end = "")
print("'s Grades")
print("English: ", end = "")
print(english)
print("Filipino: ", end = "")
print(filipino)
print("Science: ", end = "")
print(science)
print("Math: ", end = "")
print(math)
print("Araling Panlipunan: ", end = "")
print(ap)
print("Physical Education: ", end = "")
print(pe)
print("Average: ", end = "")
print(average)