name=input("Enter your name: ")
age=int(input("Enter your age: "))
address=input("Enter your address: ")
print(" ")
print(name,"'s Information")
print("Name:", name)
print("Age:", age)
print("Address:", address)